const pool = require("./pool");

const parts = [
  // cpu
  {
    category: "cpu",
    name: "Intel Core i9-13900K",
    brand: "Intel",
    tier: "flagship",
    price: 589,
    specs: {
      socket: "LGA1700",
      cores: 24,
      threads: 32,
      base_clock: 3.0,
      boost_clock: 5.8,
      tdp: 125,
      process: "Intel 7",
      cache: "36MB",
    },
    extra: {
      socket: "LGA1700",
      cores: 24,
      threads: 32,
      baseClock: 3.0,
      boostClock: 5.8,
      tdp: 125,
    },
  },
  {
    category: "cpu",
    name: "AMD Ryzen 9 7950X",
    brand: "AMD",
    tier: "flagship",
    price: 699,
    specs: {
      socket: "AM5",
      cores: 16,
      threads: 32,
      base_clock: 4.5,
      boost_clock: 5.7,
      tdp: 170,
      process: "5nm TSMC",
      cache: "64MB",
    },
    extra: {
      socket: "AM5",
      cores: 16,
      threads: 32,
      baseClock: 4.5,
      boostClock: 5.7,
      tdp: 170,
    },
  },
  {
    category: "cpu",
    name: "Intel Core i7-13700K",
    brand: "Intel",
    tier: "high-end",
    price: 409,
    specs: {
      socket: "LGA1700",
      cores: 16,
      threads: 24,
      base_clock: 3.4,
      boost_clock: 5.4,
      tdp: 125,
      process: "Intel 7",
      cache: "30MB",
    },
    extra: {
      socket: "LGA1700",
      cores: 16,
      threads: 24,
      baseClock: 3.4,
      boostClock: 5.4,
      tdp: 125,
    },
  },
  {
    category: "cpu",
    name: "AMD Ryzen 7 7700X",
    brand: "AMD",
    tier: "high-end",
    price: 399,
    specs: {
      socket: "AM5",
      cores: 8,
      threads: 16,
      base_clock: 4.5,
      boost_clock: 5.4,
      tdp: 105,
      process: "5nm TSMC",
      cache: "32MB",
    },
    extra: {
      socket: "AM5",
      cores: 8,
      threads: 16,
      baseClock: 4.5,
      boostClock: 5.4,
      tdp: 105,
    },
  },
  {
    category: "cpu",
    name: "Intel Core i5-13600K",
    brand: "Intel",
    tier: "mid-range",
    price: 319,
    specs: {
      socket: "LGA1700",
      cores: 14,
      threads: 20,
      base_clock: 3.5,
      boost_clock: 5.1,
      tdp: 125,
      process: "Intel 7",
      cache: "24MB",
    },
    extra: {
      socket: "LGA1700",
      cores: 14,
      threads: 20,
      baseClock: 3.5,
      boostClock: 5.1,
      tdp: 125,
    },
  },
  {
    category: "cpu",
    name: "AMD Ryzen 5 7600X",
    brand: "AMD",
    tier: "mid-range",
    price: 299,
    specs: {
      socket: "AM5",
      cores: 6,
      threads: 12,
      base_clock: 4.7,
      boost_clock: 5.3,
      tdp: 105,
      process: "5nm TSMC",
      cache: "32MB",
    },
    extra: {
      socket: "AM5",
      cores: 6,
      threads: 12,
      baseClock: 4.7,
      boostClock: 5.3,
      tdp: 105,
    },
  },
  {
    category: "cpu",
    name: "Intel Core i3-13100",
    brand: "Intel",
    tier: "budget",
    price: 149,
    specs: {
      socket: "LGA1700",
      cores: 4,
      threads: 8,
      base_clock: 3.4,
      boost_clock: 4.5,
      tdp: 60,
      process: "Intel 7",
      cache: "12MB",
    },
    extra: {
      socket: "LGA1700",
      cores: 4,
      threads: 8,
      baseClock: 3.4,
      boostClock: 4.5,
      tdp: 60,
    },
  },
  {
    category: "cpu",
    name: "AMD Ryzen 5 5600",
    brand: "AMD",
    tier: "budget",
    price: 149,
    specs: {
      socket: "AM4",
      cores: 6,
      threads: 12,
      base_clock: 3.5,
      boost_clock: 4.4,
      tdp: 65,
      process: "7nm TSMC",
      cache: "32MB",
    },
    extra: {
      socket: "AM4",
      cores: 6,
      threads: 12,
      baseClock: 3.5,
      boostClock: 4.4,
      tdp: 65,
    },
  },

  // board
  {
    category: "motherboard",
    name: "ASUS ROG Maximus Z790 Hero",
    brand: "ASUS",
    tier: "flagship",
    price: 629,
    specs: {
      socket: "LGA1700",
      chipset: "Z790",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 5.0",
      m2_slots: 4,
    },
    extra: {
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "MSI MEG X670E ACE",
    brand: "MSI",
    tier: "flagship",
    price: 599,
    specs: {
      socket: "AM5",
      chipset: "X670E",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 5.0",
      m2_slots: 4,
    },
    extra: {
      socket: "AM5",
      chipset: "X670E",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "Gigabyte Z790 AORUS Elite AX",
    brand: "Gigabyte",
    tier: "high-end",
    price: 329,
    specs: {
      socket: "LGA1700",
      chipset: "Z790",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 5.0",
      m2_slots: 3,
    },
    extra: {
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "ASUS TUF Gaming X670E-Plus",
    brand: "ASUS",
    tier: "high-end",
    price: 299,
    specs: {
      socket: "AM5",
      chipset: "X670E",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 5.0",
      m2_slots: 3,
    },
    extra: {
      socket: "AM5",
      chipset: "X670E",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "MSI PRO Z790-A WiFi",
    brand: "MSI",
    tier: "mid-range",
    price: 229,
    specs: {
      socket: "LGA1700",
      chipset: "Z790",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 4.0",
      m2_slots: 2,
    },
    extra: {
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "Gigabyte B650 AORUS Elite AX",
    brand: "Gigabyte",
    tier: "mid-range",
    price: 219,
    specs: {
      socket: "AM5",
      chipset: "B650",
      form_factor: "ATX",
      memory_slots: 4,
      max_memory: 128,
      pcie: "PCIe 4.0",
      m2_slots: 2,
    },
    extra: {
      socket: "AM5",
      chipset: "B650",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: 128,
    },
  },
  {
    category: "motherboard",
    name: "ASRock B760M Pro RS",
    brand: "ASRock",
    tier: "budget",
    price: 119,
    specs: {
      socket: "LGA1700",
      chipset: "B760",
      form_factor: "mATX",
      memory_slots: 2,
      max_memory: 64,
      pcie: "PCIe 4.0",
      m2_slots: 2,
    },
    extra: {
      socket: "LGA1700",
      chipset: "B760",
      formFactor: "mATX",
      memorySlots: 2,
      maxMemory: 64,
    },
  },
  {
    category: "motherboard",
    name: "MSI PRO B550M-VC WiFi",
    brand: "MSI",
    tier: "budget",
    price: 109,
    specs: {
      socket: "AM4",
      chipset: "B550",
      form_factor: "mATX",
      memory_slots: 2,
      max_memory: 64,
      pcie: "PCIe 4.0",
      m2_slots: 2,
    },
    extra: {
      socket: "AM4",
      chipset: "B550",
      formFactor: "mATX",
      memorySlots: 2,
      maxMemory: 64,
    },
  },

  // gpu
  {
    category: "gpu",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    tier: "flagship",
    price: 1599,
    specs: {
      vram: 24,
      memory_type: "GDDR6X",
      tdp: 450,
      cuda_cores: 16384,
      boost_clock: "2.52 GHz",
      bus: "384-bit",
    },
    extra: { vram: 24, memoryType: "GDDR6X", tdp: 450 },
  },
  {
    category: "gpu",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    tier: "flagship",
    price: 999,
    specs: {
      vram: 24,
      memory_type: "GDDR6",
      tdp: 355,
      compute_units: 96,
      boost_clock: "2.5 GHz",
      bus: "384-bit",
    },
    extra: { vram: 24, memoryType: "GDDR6", tdp: 355 },
  },
  {
    category: "gpu",
    name: "NVIDIA GeForce RTX 4080",
    brand: "NVIDIA",
    tier: "high-end",
    price: 1199,
    specs: {
      vram: 16,
      memory_type: "GDDR6X",
      tdp: 320,
      cuda_cores: 9728,
      boost_clock: "2.51 GHz",
      bus: "256-bit",
    },
    extra: { vram: 16, memoryType: "GDDR6X", tdp: 320 },
  },
  {
    category: "gpu",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    tier: "high-end",
    price: 499,
    specs: {
      vram: 16,
      memory_type: "GDDR6",
      tdp: 263,
      compute_units: 60,
      boost_clock: "2.43 GHz",
      bus: "256-bit",
    },
    extra: { vram: 16, memoryType: "GDDR6", tdp: 263 },
  },
  {
    category: "gpu",
    name: "NVIDIA GeForce RTX 4070",
    brand: "NVIDIA",
    tier: "mid-range",
    price: 599,
    specs: {
      vram: 12,
      memory_type: "GDDR6X",
      tdp: 200,
      cuda_cores: 5888,
      boost_clock: "2.48 GHz",
      bus: "192-bit",
    },
    extra: { vram: 12, memoryType: "GDDR6X", tdp: 200 },
  },
  {
    category: "gpu",
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    tier: "mid-range",
    price: 269,
    specs: {
      vram: 8,
      memory_type: "GDDR6",
      tdp: 165,
      compute_units: 32,
      boost_clock: "2.655 GHz",
      bus: "128-bit",
    },
    extra: { vram: 8, memoryType: "GDDR6", tdp: 165 },
  },
  {
    category: "gpu",
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    tier: "budget",
    price: 299,
    specs: {
      vram: 8,
      memory_type: "GDDR6",
      tdp: 115,
      cuda_cores: 3072,
      boost_clock: "2.46 GHz",
      bus: "128-bit",
    },
    extra: { vram: 8, memoryType: "GDDR6", tdp: 115 },
  },
  {
    category: "gpu",
    name: "AMD Radeon RX 6600",
    brand: "AMD",
    tier: "budget",
    price: 199,
    specs: {
      vram: 8,
      memory_type: "GDDR6",
      tdp: 132,
      compute_units: 28,
      boost_clock: "2.491 GHz",
      bus: "128-bit",
    },
    extra: { vram: 8, memoryType: "GDDR6", tdp: 132 },
  },

  // ram
  {
    category: "ram",
    name: "Corsair Dominator Titanium DDR5-7200",
    brand: "Corsair",
    tier: "flagship",
    price: 399,
    specs: {
      capacity: 64,
      speed: 7200,
      type: "DDR5",
      modules: "2x32GB",
      latency: "CL34",
      voltage: "1.4V",
    },
    extra: { capacity: 64, speed: 7200, type: "DDR5" },
  },
  {
    category: "ram",
    name: "G.Skill Trident Z5 RGB DDR5-6400",
    brand: "G.Skill",
    tier: "high-end",
    price: 199,
    specs: {
      capacity: 32,
      speed: 6400,
      type: "DDR5",
      modules: "2x16GB",
      latency: "CL32",
      voltage: "1.35V",
    },
    extra: { capacity: 32, speed: 6400, type: "DDR5" },
  },
  {
    category: "ram",
    name: "Kingston Fury Beast DDR5-5200",
    brand: "Kingston",
    tier: "mid-range",
    price: 129,
    specs: {
      capacity: 32,
      speed: 5200,
      type: "DDR5",
      modules: "2x16GB",
      latency: "CL40",
      voltage: "1.25V",
    },
    extra: { capacity: 32, speed: 5200, type: "DDR5" },
  },
  {
    category: "ram",
    name: "Corsair Vengeance DDR4-3600",
    brand: "Corsair",
    tier: "mid-range",
    price: 89,
    specs: {
      capacity: 32,
      speed: 3600,
      type: "DDR4",
      modules: "2x16GB",
      latency: "CL18",
      voltage: "1.35V",
    },
    extra: { capacity: 32, speed: 3600, type: "DDR4" },
  },
  {
    category: "ram",
    name: "G.Skill Ripjaws V DDR4-3200",
    brand: "G.Skill",
    tier: "budget",
    price: 49,
    specs: {
      capacity: 16,
      speed: 3200,
      type: "DDR4",
      modules: "2x8GB",
      latency: "CL16",
      voltage: "1.35V",
    },
    extra: { capacity: 16, speed: 3200, type: "DDR4" },
  },
  {
    category: "ram",
    name: "Crucial Pro DDR5-5600",
    brand: "Crucial",
    tier: "mid-range",
    price: 109,
    specs: {
      capacity: 32,
      speed: 5600,
      type: "DDR5",
      modules: "2x16GB",
      latency: "CL46",
      voltage: "1.1V",
    },
    extra: { capacity: 32, speed: 5600, type: "DDR5" },
  },

  // storage
  {
    category: "storage",
    name: "Samsung 990 Pro 2TB",
    brand: "Samsung",
    tier: "flagship",
    price: 179,
    specs: {
      capacity: 2000,
      type: "NVMe SSD",
      interface: "PCIe 4.0 x4",
      read_speed: 7450,
      write_speed: 6900,
      form_factor: "M.2 2280",
    },
    extra: {
      capacity: 2000,
      type: "NVMe SSD",
      readSpeed: 7450,
      writeSpeed: 6900,
    },
  },
  {
    category: "storage",
    name: "WD Black SN850X 2TB",
    brand: "Western Digital",
    tier: "flagship",
    price: 169,
    specs: {
      capacity: 2000,
      type: "NVMe SSD",
      interface: "PCIe 4.0 x4",
      read_speed: 7300,
      write_speed: 6600,
      form_factor: "M.2 2280",
    },
    extra: {
      capacity: 2000,
      type: "NVMe SSD",
      readSpeed: 7300,
      writeSpeed: 6600,
    },
  },
  {
    category: "storage",
    name: "Seagate FireCuda 530 1TB",
    brand: "Seagate",
    tier: "high-end",
    price: 109,
    specs: {
      capacity: 1000,
      type: "NVMe SSD",
      interface: "PCIe 4.0 x4",
      read_speed: 7300,
      write_speed: 6000,
      form_factor: "M.2 2280",
    },
    extra: {
      capacity: 1000,
      type: "NVMe SSD",
      readSpeed: 7300,
      writeSpeed: 6000,
    },
  },
  {
    category: "storage",
    name: "Samsung 870 EVO 1TB",
    brand: "Samsung",
    tier: "mid-range",
    price: 89,
    specs: {
      capacity: 1000,
      type: "SATA SSD",
      interface: "SATA III",
      read_speed: 560,
      write_speed: 530,
      form_factor: "2.5-inch",
    },
    extra: {
      capacity: 1000,
      type: "SATA SSD",
      readSpeed: 560,
      writeSpeed: 530,
    },
  },
  {
    category: "storage",
    name: "Kingston NV2 500GB",
    brand: "Kingston",
    tier: "budget",
    price: 49,
    specs: {
      capacity: 500,
      type: "NVMe SSD",
      interface: "PCIe 4.0 x4",
      read_speed: 3500,
      write_speed: 2100,
      form_factor: "M.2 2280",
    },
    extra: {
      capacity: 500,
      type: "NVMe SSD",
      readSpeed: 3500,
      writeSpeed: 2100,
    },
  },
  {
    category: "storage",
    name: "Seagate Barracuda 4TB",
    brand: "Seagate",
    tier: "budget",
    price: 79,
    specs: {
      capacity: 4000,
      type: "HDD",
      interface: "SATA III",
      read_speed: 190,
      write_speed: 190,
      form_factor: "3.5-inch",
    },
    extra: { capacity: 4000, type: "HDD", readSpeed: 190, writeSpeed: 190 },
  },

  // psu
  {
    category: "psu",
    name: "Corsair HX1200i Platinum",
    brand: "Corsair",
    tier: "flagship",
    price: 329,
    specs: {
      wattage: 1200,
      efficiency: "80+ Platinum",
      modular: "Fully Modular",
      fan_size: "135mm",
    },
    extra: {
      wattage: 1200,
      efficiency: "80+ Platinum",
      modular: "Fully Modular",
    },
  },
  {
    category: "psu",
    name: "be quiet! Dark Power 13 1000W",
    brand: "be quiet!",
    tier: "flagship",
    price: 279,
    specs: {
      wattage: 1000,
      efficiency: "80+ Titanium",
      modular: "Fully Modular",
      fan_size: "135mm",
    },
    extra: {
      wattage: 1000,
      efficiency: "80+ Titanium",
      modular: "Fully Modular",
    },
  },
  {
    category: "psu",
    name: "EVGA SuperNOVA 850 G6",
    brand: "EVGA",
    tier: "high-end",
    price: 149,
    specs: {
      wattage: 850,
      efficiency: "80+ Gold",
      modular: "Fully Modular",
      fan_size: "140mm",
    },
    extra: { wattage: 850, efficiency: "80+ Gold", modular: "Fully Modular" },
  },
  {
    category: "psu",
    name: "Seasonic Focus GX-750",
    brand: "Seasonic",
    tier: "mid-range",
    price: 129,
    specs: {
      wattage: 750,
      efficiency: "80+ Gold",
      modular: "Fully Modular",
      fan_size: "120mm",
    },
    extra: { wattage: 750, efficiency: "80+ Gold", modular: "Fully Modular" },
  },
  {
    category: "psu",
    name: "Corsair CV650",
    brand: "Corsair",
    tier: "budget",
    price: 69,
    specs: {
      wattage: 650,
      efficiency: "80+ Bronze",
      modular: "Non-Modular",
      fan_size: "120mm",
    },
    extra: { wattage: 650, efficiency: "80+ Bronze", modular: "Non-Modular" },
  },
  {
    category: "psu",
    name: "NZXT C750 Gold",
    brand: "NZXT",
    tier: "mid-range",
    price: 109,
    specs: {
      wattage: 750,
      efficiency: "80+ Gold",
      modular: "Fully Modular",
      fan_size: "135mm",
    },
    extra: { wattage: 750, efficiency: "80+ Gold", modular: "Fully Modular" },
  },

  // cases
  {
    category: "case",
    name: "Lian Li O11 Dynamic EVO XL",
    brand: "Lian Li",
    tier: "flagship",
    price: 199,
    specs: {
      type: "Full Tower",
      form_factors: ["E-ATX", "ATX", "mATX"],
      max_radiator: "480mm",
      fan_slots: 10,
    },
    extra: { type: "Full Tower", formFactor: ["E-ATX", "ATX", "mATX"] },
  },
  {
    category: "case",
    name: "Fractal Design Torrent",
    brand: "Fractal Design",
    tier: "flagship",
    price: 189,
    specs: {
      type: "Mid Tower",
      form_factors: ["E-ATX", "ATX", "mATX"],
      max_radiator: "420mm",
      fan_slots: 9,
    },
    extra: { type: "Mid Tower", formFactor: ["E-ATX", "ATX", "mATX"] },
  },
  {
    category: "case",
    name: "NZXT H7 Flow",
    brand: "NZXT",
    tier: "high-end",
    price: 129,
    specs: {
      type: "Mid Tower",
      form_factors: ["ATX", "mATX", "Mini-ITX"],
      max_radiator: "360mm",
      fan_slots: 6,
    },
    extra: { type: "Mid Tower", formFactor: ["ATX", "mATX", "Mini-ITX"] },
  },
  {
    category: "case",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    tier: "mid-range",
    price: 104,
    specs: {
      type: "Mid Tower",
      form_factors: ["ATX", "mATX", "Mini-ITX"],
      max_radiator: "360mm",
      fan_slots: 6,
    },
    extra: { type: "Mid Tower", formFactor: ["ATX", "mATX", "Mini-ITX"] },
  },
  {
    category: "case",
    name: "be quiet! Pure Base 500DX",
    brand: "be quiet!",
    tier: "mid-range",
    price: 109,
    specs: {
      type: "Mid Tower",
      form_factors: ["ATX", "mATX", "Mini-ITX"],
      max_radiator: "360mm",
      fan_slots: 7,
    },
    extra: { type: "Mid Tower", formFactor: ["ATX", "mATX", "Mini-ITX"] },
  },
  {
    category: "case",
    name: "Phanteks P300A",
    brand: "Phanteks",
    tier: "budget",
    price: 59,
    specs: {
      type: "Mid Tower",
      form_factors: ["ATX", "mATX"],
      max_radiator: "280mm",
      fan_slots: 4,
    },
    extra: { type: "Mid Tower", formFactor: ["ATX", "mATX"] },
  },

  // coolers
  {
    category: "cooler",
    name: "NZXT Kraken Elite 360",
    brand: "NZXT",
    tier: "flagship",
    price: 269,
    specs: {
      type: "AIO Liquid",
      radiator_size: 360,
      tdp_support: 500,
      compatible_sockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
      fans: "3x120mm",
    },
    extra: {
      type: "AIO Liquid",
      radiatorSize: 360,
      tdpSupport: 500,
      compatibleSockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
    },
  },
  {
    category: "cooler",
    name: "Corsair iCUE H150i Elite",
    brand: "Corsair",
    tier: "high-end",
    price: 199,
    specs: {
      type: "AIO Liquid",
      radiator_size: 360,
      tdp_support: 400,
      compatible_sockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
      fans: "3x120mm",
    },
    extra: {
      type: "AIO Liquid",
      radiatorSize: 360,
      tdpSupport: 400,
      compatibleSockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
    },
  },
  {
    category: "cooler",
    name: "Noctua NH-D15",
    brand: "Noctua",
    tier: "high-end",
    price: 99,
    specs: {
      type: "Air Cooler",
      radiator_size: null,
      tdp_support: 250,
      compatible_sockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
      fans: "2x140mm",
    },
    extra: {
      type: "Air Cooler",
      radiatorSize: null,
      tdpSupport: 250,
      compatibleSockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
    },
  },
  {
    category: "cooler",
    name: "DeepCool AG620 ARGB",
    brand: "DeepCool",
    tier: "mid-range",
    price: 49,
    specs: {
      type: "Air Cooler",
      radiator_size: null,
      tdp_support: 220,
      compatible_sockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
      fans: "2x120mm",
    },
    extra: {
      type: "Air Cooler",
      radiatorSize: null,
      tdpSupport: 220,
      compatibleSockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
    },
  },
  {
    category: "cooler",
    name: "Cooler Master Hyper 212",
    brand: "Cooler Master",
    tier: "budget",
    price: 34,
    specs: {
      type: "Air Cooler",
      radiator_size: null,
      tdp_support: 150,
      compatible_sockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
      fans: "1x120mm",
    },
    extra: {
      type: "Air Cooler",
      radiatorSize: null,
      tdpSupport: 150,
      compatibleSockets: ["LGA1700", "LGA1200", "AM5", "AM4"],
    },
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log("Seeding parts...");
    await client.query("DELETE FROM parts");
    for (const p of parts) {
      await client.query(
        `INSERT INTO parts (category, name, brand, tier, price, specs, extra)
         VALUES ($1,$2,$3,$4,$5,$6,$7)`,
        [
          p.category,
          p.name,
          p.brand,
          p.tier,
          p.price,
          JSON.stringify(p.specs),
          JSON.stringify(p.extra),
        ],
      );
    }
    console.log("✅ Seeded", parts.length, "parts");
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
